version: '2'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: django
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql-custom.cnf:/etc/mysql/conf.d/mysql-custom.cnf

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ./mysql_timeout:/code
    ports:
      - 8000:80
#    command: ./manage.py migrate
    depends_on:
      - db